# Simple workflow for deploying static content to GitHub Pages
# adapted from https://github.com/actions/starter-workflows/blob/main/pages/static.yml
name: Build and Deploy to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [master]

  # Every day at 2:47am (in case Patreon list changes)
  schedule:
    - cron: "47 2 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: apt installs
        run: sudo apt update && sudo apt install -y texlive-latex-extra pdf2svg

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: pip installs
        run: pip install -r requirements.txt

      - name: Build English
        run: make html
        env:
          CREATOR_ID: ${{ secrets.CREATOR_ID }}

      - name: Zip just English version for Release
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r html.zip ./_build

      - name: Build Dutch
        run: make html-nl
        env:
          CREATOR_ID: ${{ secrets.CREATOR_ID }}

      - name: Build French
        run: make html-fr
        env:
          CREATOR_ID: ${{ secrets.CREATOR_ID }}

      - name: Build Ukraine
        run: make html-ukraine
        env:
          CREATOR_ID: ${{ secrets.CREATOR_ID }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './_build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')" && echo "::set-output name=day::$(day +'%d')"

      - name: Create Release with zip file only on first day of each month
        uses: softprops/action-gh-release@v1
        if: ${{ steps.date.outputs.day == '01' }}
        with:
          files: html.zip
          tag_name: ${{ steps.date.outputs.date }}
